### ISSUE TITLE
Error in /admin/users

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/amadaa-server#108]
```
Traceback (most recent call last):
  File "/home/lorenzo/Progetti/amadaa-server/ENV/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/lorenzo/Progetti/amadaa-server/ENV/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/lorenzo/Progetti/amadaa-server/ENV/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/lorenzo/Progetti/amadaa-server/amadaa/user/admin/app.py", line 9, in index
    'users': get_all_users()
  File "/home/lorenzo/Progetti/amadaa-server/amadaa/user/app.py", line 256, in get_all_users
    u = User()
  File "/home/lorenzo/Progetti/amadaa-server/amadaa/user/app.py", line 103, in __init__
    self.last_login = last_login
  File "/home/lorenzo/Progetti/amadaa-server/amadaa/base.py", line 44, in __setattr__
    raise Exception("set: no such attribute")
Exception: set: no such attribute
```

**Comment by lcabrini** [comment]
*sigh*  there are still remnants left of last_login.
